name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npx turbo build
        
      - name: Release Core Package
        working-directory: packages/tree-chart-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git diff --quiet HEAD~ HEAD ./
          if [ $? -ne 0 ]; then
            npm run release
          else
            echo "No changes in tree-chart-core, skipping release"
          fi
          
      - name: Release Vue Package
        working-directory: packages/vue3-tree-chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git diff --quiet HEAD~ HEAD ./ || git diff --quiet HEAD~ HEAD ../tree-chart-core/
          if [ $? -ne 0 ]; then
            npm run release
          else
            echo "No changes affecting vue3-tree-chart, skipping release"
          fi